### ISSUE TITLE
OutOfMemory stack trace

### ISSUE THREAD

**Issue by youngl98** [gwhalin/Memcached-Java-Client#13]
In our production system, we have seen the following stack trace recently.  We running the latest Memcached-Java-Client binary version 2.5.1.

2010-07-02 18:43:03 [TP-Processor61] ERROR c.s.j.s.c.ContainerResponse - The exception contained within MappableContainerException could not be mapped to a response, re-throwing to the HTTP container 
java.lang.OutOfMemoryError: Direct buffer memory 
at java.nio.Bits.reserveMemory(Bits.java:633) ~[na:1.6.0_18] 
at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:95) ~[na:1.6.0_18] 
at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:288) ~[na:1.6.0_18] 
at com.schooner.MemCached.SchoonerSockIOPool$TCPSockIO.<init>(Unknown Source) ~[memcached-client-2.5.1.jar:na] 
at com.schooner.MemCached.SchoonerSockIOPool.createSocketWithAdd(Unknown Source) ~[memcached-client-2.5.1.jar:na] 
at com.schooner.MemCached.SchoonerSockIOPool.getConnection(Unknown Source) ~[memcached-client-2.5.1.jar:na] 
at com.schooner.MemCached.SchoonerSockIOPool.getSock(Unknown Source) ~[memcached-client-2.5.1.jar:na] 
at com.schooner.MemCached.BinaryClient.get(Unknown Source) ~[memcached-client-2.5.1.jar:na] 
at com.schooner.MemCached.BinaryClient.get(Unknown Source) ~[memcached-client-2.5.1.jar:na] 
at com.schooner.MemCached.BinaryClient.get(Unknown Source) ~[memcached-client-2.5.1.jar:na] 
at com.danga.MemCached.MemCachedClient.get(Unknown Source) ~[memcached-client-2.5.1.jar:na]

**Comment by newroot** [comment]
Hi, young,

From the error trace, I found that the error was caused by creating socket in the source code.
As you know, the default size of the connection pool in memcached java client is 32.

If you are running this client with higher concurrency, please try to give a bigger connection pool size.

Try 

pool.setMaxConn(128);

And specify more memory (-Xmx) to the jvm.

Thanks.

If it didn't fix the issue, please let me know.

**Comment by youngl98** [comment]
We have been running with pool.setMaxConn(128); for the last three months.  so far we haven't had the OOM exception.

Looks like this solved the problem.

**Comment by andrden** [comment]
Thanks for the driver, and I want to add my 2 cents.

For the same problem we went another way - I replaced all allocateDirect() with allocate() in source - and now running with that patch. 

That's because java's GC and direct buffers are bad combination on multi-gigabyte servers. We try to avoid full GC to have production server run smoothly and as a result it just fails to collect direct buffers! In main heap references to them are small and GC not interested, but meanwhile process size in Linux top is much more than -Xmx and Linux box starts swapping. 

Actually I would consider direct buffers harmful overall because of this GC issue - heap byte buffers are safer, more consistent with GC and no slowdown was observed in production with them

Thanks again

**Comment by newroot** [comment]
Exactly, I agree with your comments.

Due to the java doc, we choose direct buffer because of its better performance.

Another reason for allocate that much memory in each connection (by default, it's 1MB for each connection in our client) is because we want to reduce one round of memory allocation. Since we have to specify the bytes size of each set command in memcached protocol; in a general way, we have to deserialize the java object and keep it in a temp memory before sending these bytes out, while the connection itself has another buffer to hold these bytes, actually,  these were duplicated allocation.

Thanks anyway for the awesome comments.
