### ISSUE TITLE
Mc socket is keep reading but no data is readed

### ISSUE THREAD

**Issue by akan** [gwhalin/Memcached-Java-Client#20]
Hi All,
         I got a strange problem using java memcached client.  I have a resin which has 512 resin-tcp-connection, all are runnable, but they are hanging at mc socket reading.  So the resin is no response, for it reaches max 512 http request. And it just happens on busy resin, which means the request num is >30/s, and the network traffic is >100Mb/s. There are 5*50=250 MC connections.It seemed that readFromChannel sometimes not work. the possiblity is less than 1/100000. 
But once it ocurr, the resin thread will keep on reading but read on data.  So these fake dead threads will be more and more.

```
   I also find someone else suffered similar problem about sun.nio.ch.FileDispatcher.read0, such as hadoop, jboss.
```

How to solve it? As the thread keep on reading but no timeout?  Now I can only restart resin every day to avoid resin no responding.

And I was confuse about the code on com.schooner.MemCached.SchoonerSockIO.java

```
// the datagram sent from memcached mustn't beyond 1400 bytes.
public ByteBuffer readBuf = ByteBuffer.allocateDirect(8 * 1024); 
```

comment: the MTU on linux is 1500 by default. why you say 1400 bytes?
if the datagram is about 1400 bytes, why sets the buff 8_1024, not 4_1024?

"resin-tcp-connection-10.67.222.61:8388-19351" daemon prio=10 tid=0x00002aabba08f800 nid=0x13c0 runnable [0x00002aabf8906000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.FileDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:233)
        at sun.nio.ch.IOUtil.read(IOUtil.java:200)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:236)
        - locked <0x00002aaadb561880> (a java.lang.Object)
        at com.schooner.MemCached.SockInputStream.readFromChannel(SockInputStream.java:124)
        at com.schooner.MemCached.SockInputStream.read(SockInputStream.java:109)
        at com.schooner.MemCached.SockInputStream.getLine(SockInputStream.java:173)
        at com.schooner.MemCached.AscIIClient.get(AscIIClient.java:771)
        at com.schooner.MemCached.AscIIClient.get(AscIIClient.java:613)
        at com.schooner.MemCached.AscIIClient.get(AscIIClient.java:609)
        at com.danga.MemCached.MemCachedClient.get(MemCachedClient.java:1047)
        at cn.org.dbcache.BaseManager.getFromMemCachedServer(BaseManager.java:1806)
        at cn.org.dbcache.BaseManager.findById(BaseManager.java:434)
        at cn.org.dbcache.BaseManager.getFromMemCachedServerList(BaseManager.java:1883)
        at cn.org.dbcache.BaseManager.loadList(BaseManager.java:1317)

**Comment by newroot** [comment]
which version are you using for the memcached client?

**Comment by esah** [comment]
I have the same problem! My application server (jetty 7) stopped the same way with the same thread dump:

"qtp248786184-1889" prio=10 tid=0x00007fa57fadd800 nid=0x246d runnable [0x00007fa581480000]
   java.lang.Thread.State: RUNNABLE
    at sun.nio.ch.FileDispatcher.read0(Native Method)
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:202)
    at sun.nio.ch.IOUtil.read(IOUtil.java:169)
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:243)
    - locked <0x00000000be622510> (a java.lang.Object)
    at com.schooner.MemCached.SockInputStream.readFromChannel(Unknown Source)
    at com.schooner.MemCached.SockInputStream.read(Unknown Source)
    at com.schooner.MemCached.SockInputStream.getLine(Unknown Source)
    at com.schooner.MemCached.AscIIClient.get(Unknown Source)
    at com.schooner.MemCached.AscIIClient.get(Unknown Source)
    at com.schooner.MemCached.AscIIClient.get(Unknown Source)
    at com.danga.MemCached.MemCachedClient.get(Unknown Source)

The bug is appeared after upgrading memcache client from 2.0.1 to 2.6.1.

It's a real problem, so i could't find solution and enforced to switch to spymemcache client.

**Comment by newroot** [comment]
HI esah,

Since we could not repeat the issue in our environment, can you switch to 2.6.0 or even previous version to verify the same issue?

**Comment by esah** [comment]
Unfortunately i can't repeat it cause the issue is appeared only in production under high load next day after release. 
All web requests to my app server are stuck. The machine has 55 tcp open connections to memcached servers. Cpu is 0% and huge free memory.
I really don't know what stay behind the bug and how to repeat it in test environment. 
Memcached version is 1.2.8-1
Protocol is text.

**Comment by jpvirolainen** [comment]
Hi, we had the same issue happen with our app cluster today. 8 out of 10 servers were stuck in the same place as the original issue in this thread.
We're running version 2.6.0.

**Comment by PiouseLeo** [comment]
Unfortunately I met the same problem. 
client version 2.5.1
memcached version 1.4.5
web server: resin-3.0.21

my stack trace:

"xxx-1-thread-1" daemon prio=10 tid=0x0000000053962000 nid=0x5cd9 runnable [0x00000000520fd000..0x00000000520fdb10]
   java.lang.Thread.State: RUNNABLE
    at sun.nio.ch.FileDispatcher.read0(Native Method)
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:233)
    at sun.nio.ch.IOUtil.read(IOUtil.java:200)
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:236)
    - locked <0x00002aab0f1e05e0> (a java.lang.Object)
    at com.schooner.MemCached.SockInputStream.readFromChannel(SockInputStream.java:124)
    at com.schooner.MemCached.SockInputStream.read(SockInputStream.java:109)
    at com.schooner.MemCached.SockInputStream.getLine(SockInputStream.java:173)  
    at com.schooner.MemCached.AscIIClient.get(AscIIClient.java:770)  
    at com.schooner.MemCached.AscIIClient.get(AscIIClient.java:612)  
    at com.schooner.MemCached.AscIIClient.get(AscIIClient.java:608)  
    at com.danga.MemCached.MemCachedClient.get(MemCachedClient.java:1047)  

I am trying to repeat this bug.

**Comment by joongonn** [comment]
In our case (using 2.6.2), our web server threads got stucked at:

"2076090123@qtp-1696446139-91312" prio=10 tid=0x00007f4970178800 nid=0x559c runnable [0x00007f493eae9000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.FileDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:202)
        at sun.nio.ch.IOUtil.read(IOUtil.java:169)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:243)
        - locked <0x00000007d44dfc48> (a java.lang.Object)
        at com.schooner.MemCached.SockInputStream.readFromChannel(SockInputStream.java:124)
        at com.schooner.MemCached.SockInputStream.read(SockInputStream.java:109)
        at com.schooner.MemCached.SockInputStream.getLine(SockInputStream.java:173)
        at com.schooner.MemCached.AscIIClient.get(AscIIClient.java:790)
        at com.schooner.MemCached.AscIIClient.get(AscIIClient.java:630)
        at com.schooner.MemCached.AscIIClient.get(AscIIClient.java:626)
        at com.danga.MemCached.MemCachedClient.get(MemCachedClient.java:1061)

Can't figure out why, as it appears, the AsciiClient didn't get back the \r\n it is waiting for from the server.

Drawing reference from http://technfun.wordpress.com/2009/01/29/networking-in-java-non-blocking-nio-blocking-nio-and-io/ , would you guys recommend a workaround, something along the lines of :

```
private final void readFromChannel() throws IOException {
    sock.readBuf.clear();
    sock.getChannel().socket().setSoTimeout(60000);
    InputStream is = sock.getChannel().socket().getInputStream();
    ReadableByteChannel wrappedChannel = Channels.newChannel(is);
    wrappedChannel.read(sock.readBuf);
    sock.readBuf.flip();
}
```

**Comment by PiouseLeo** [comment]
Hi，

I guess that it's not the real reason.

Code "return b & 0xff;" and "return (b & 0xff;)" will return the same value.

thx

On Fri, Nov 25, 2011 at 12:31 PM, Xingen Wang <
reply@reply.github.com

**Comment by hjdongxuxu** [comment]
Hi,

I guess that the reason maybe: When you analyse the response you don't  handle the error case like:
GET (key is a blank string)
ERROR

All the contents have been readed out, but you don't handle this error case and continue to read the response. So when call input.getLine();-->read()-->readFromChannel() no content will come and the thread will hang at:"sock.getChannel().read(sock.readBuf);".

**Comment by newroot** [comment]
I think the hang issue is caused by http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=4614802.

We are using the nio in incorrect way. I will figure out a small patch, but perhaps decrease the performance a little bit.

Thanks for joongonn.

Add lines in readFromChannel

```
ReadableByteChannel wrappedChannel = Channels.newChannel(is);
wrappedChannel.read(sock.readBuf);
```
