### ISSUE TITLE
NullPointerException in getMulti while some concurrent calls to a SchoonerSockIOPool

### ISSUE THREAD

**Issue by dracoyang** [gwhalin/Memcached-Java-Client#24]
Hi, Everyone:  
    I made a minor change on MemcachedPerfTest to test 'getMulti' instead of  'get', and then when I run the tests using thread number 50, runs number 100, I got the following exception sometimes:  

<pre>
Exception in thread "Thread-0" java.lang.NullPointerException
    at com.schooner.MemCached.AscIIClient$NIOLoader.doMulti(AscIIClient.java:1522)
    at com.schooner.MemCached.AscIIClient.getMulti(AscIIClient.java:1082)
    at com.schooner.MemCached.AscIIClient.getMulti(AscIIClient.java:1005)
    at com.danga.MemCached.MemCachedClient.getMulti(MemCachedClient.java:1207)
    at com.danga.MemCached.MemCachedClient.getMulti(MemCachedClient.java:1188)
    at com.schooner.MemCached.MemcachedPerfTest$bench.run(MemcachedPerfTest.java:123)
</pre>  

Then I did some researches and found there's a bug:  

<pre>
        try {
#1458       selector = Selector.open();

            // get the sockets, flip them to non-blocking, and set up data
            // structures
#1462       conns = new Connection[sockKeys.keySet().size()];
            ...
    } catch (IOException e) {
#1508       e.printStackTrace();
            return;
        } finally {
            ....
#1522       for (Connection c : conns) {
                if (c != null)
                    c.close();
                }
            }
        }
</pre>

The exception occurred at #1522, it means conns is null, the possible reason is #1458 threw an exception and was not successfully run, so I added code #1508 for tracing the reason, and I got the stack of real exception:  

<pre>
 java.io.IOException: Unable to establish loopback connection
    at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:106)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:122)
    at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:27)
    at java.nio.channels.Pipe.open(Pipe.java:133)
    at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:104)
    at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:26)
    at java.nio.channels.Selector.open(Selector.java:209)
    at com.schooner.MemCached.AscIIClient$NIOLoader.doMulti(AscIIClient.java:1458)
    at com.schooner.MemCached.AscIIClient.getMulti(AscIIClient.java:1082)
    at com.schooner.MemCached.AscIIClient.getMulti(AscIIClient.java:1005)
    at com.danga.MemCached.MemCachedClient.getMulti(MemCachedClient.java:1207)
    at com.danga.MemCached.MemCachedClient.getMulti(MemCachedClient.java:1188)
    at com.schooner.MemCached.MemcachedPerfTest$bench.run(MemcachedPerfTest.java:123)
Caused by: java.net.BindException: Address already in use: connect
    at sun.nio.ch.Net.connect(Native Method)
    at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:507)
    at java.nio.channels.SocketChannel.open(SocketChannel.java:146)
    at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:78)
    ... 13 more
</pre>

Not sure why nio throws out this exception, probably the concurrent load is too high?(but I don't think 50 concurrent is very high ), anyway I think we should not let null pointer exception happen, it's a bug.

**Comment by mengli** [comment]
Hi dracoyang,
I have tried to use getMulti in perfTest, no issue found. Is there some wrong with your memcached server? I saw that the client can't connect to the server correctly in the log.

Meng Lee

**Comment by dracoyang** [comment]
No, my memcache server works fine, the exception occurs seldom and only when there're lots of concurrent calls, as mentioned I used 50 threads and each thread runs 'getMulti' 100 times for a test, the exception only occurred 1 or 2 times in each test.
