### ISSUE TITLE
Errors and bugs when memcached server(s) recycled.

### ISSUE THREAD

**Issue by bhargavmist** [gwhalin/Memcached-Java-Client#31]
Hi,

We are using the memcached client as part of our client which maintains dedicated connection via memcached client pool to memcached servers.

We observed that when the memcached servers are recycled, the connection pool on the client side becomes stale. The client will understand this only when its ready to write an entry to the recycled memcached server(s). The process of re-establishing/refreshing the client pool takes around 2 failed requests. The third consecutive request goes through.

First Request:

The first request fails with the following exception which is caught but swallowed in the catch(RuntimeException e) block in BinaryClient::set(byte opcode, String key, Object value, Date expiry, Integer hashCode, long casUnique, boolean asString) method.

Exception:
java.nio.BufferUnderflowException
    at java.nio.Buffer.nextGetIndex(Buffer.java:474)
    at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:208)
    at com.schooner.MemCached.SockInputStream.read(SockInputStream.java:110)
    at java.io.DataInputStream.readInt(DataInputStream.java:370)
    at com.schooner.MemCached.BinaryClient.set(BinaryClient.java:420)
    at com.schooner.MemCached.BinaryClient.add(BinaryClient.java:249)
    at com.danga.MemCached.MemCachedClient.add(MemCachedClient.java:568)

Second Request:

The second request fails with exception 

java.io.IOException: Broken pipe
    at sun.nio.ch.FileDispatcher.write0(Native Method)
    at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:29)
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:72)
    at sun.nio.ch.IOUtil.write(IOUtil.java:28)
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:334)
    at com.schooner.MemCached.SchoonerSockIOPool$TCPSockIO.flush(SchoonerSockIOPool.java:3077)
    at com.schooner.MemCached.BinaryClient.set(BinaryClient.java:417)
    at com.schooner.MemCached.BinaryClient.add(BinaryClient.java:249)
    at com.danga.MemCached.MemCachedClient.add(MemCachedClient.java:568)

We tried to set the errorhandler but were not able to receive the callback.

Third Request: Success.

The current implementation leaves at least two failed requests per memcached server, when the sevrers are recycled.

Is it possible to:
1) modify the code and throw the RuntimeException and IOException out so that we can catch it in our code and mitigate it ?
2) Add an api through which we can check if a particular server is up or not ?

Thank you for your help.

Regards.
Bhargav.

**Comment by mengli** [comment]
Hi bhargavmist,

I think it is reasonable to have just 2 failed requests when server recycled.
And if we change the exception handling mechanism and throw out the exceptions, this could make some compile error when users upgrade their memcached java client because they have to catch and handle exception by themselves. So this could cause some compatible problem.

Is this very important to your project?

Meng Li

**Comment by bhargavmist** [comment]
Hi mengli,

Well yeah that should be fine. Thank you.

Regards,
Bhargav.

**Comment by bpingchang** [comment]
1. you can not throw exception in errorhandler if you hava used ErrorHandler, because the CLOSE_WAIT connection cannot be closed.
2. when server(s) recycled, the connection status in client machine will becom to CLOSE_WAIT, the  CLOSE_WAIT status will disappear when reuse the connection.
