### ISSUE TITLE
infinite loop caused by IdentityHashMap

### ISSUE THREAD

**Issue by chihuanqi** [gwhalin/Memcached-Java-Client#36]
Memcached-Java-Client 1.6 
java version "1.6.0_03"
Java(TM) SE Runtime Environment (build 1.6.0_03-b05)
Java HotSpot(TM) Client VM (build 1.6.0_03-b05, mixed mode, sharing)

It's IdentityHashMap bug in the IdentityHashMapIterator.remove() method in jdk5, 6, 
can also see https://issues.apache.org/jira/browse/DIRMINA-452, http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6612102

can change the use of Memcached-Java-Client?

call stack
"worker-15" daemon prio=10 tid=0x080f1800 nid=0x2d6b runnable [0xb483f000..0xb483ffb0]
   java.lang.Thread.State: RUNNABLE
    at java.util.IdentityHashMap.put(IdentityHashMap.java:421)
    at com.danga.MemCached.SockIOPool.addSocketToPool(SockIOPool.java:961)
    at com.danga.MemCached.SockIOPool.checkIn(SockIOPool.java:1045)
    - locked <0x727fccc0> (a com.danga.MemCached.SockIOPool)
    at com.danga.MemCached.SockIOPool.checkIn(SockIOPool.java:1060)
    at com.danga.MemCached.SockIOPool$SockIO.close(SockIOPool.java:1520)
    at com.danga.MemCached.MemCachedClient.set(MemCachedClient.java:780)
    at com.danga.MemCached.MemCachedClient.set(MemCachedClient.java:473)

**Comment by newroot** [comment]
You can have a try of the performance branch, you just download binary from this web site.

**Comment by zmokhtar** [comment]
I have corrected this issue in my fork by creating a set of items and then removing them in a separate loop.

https://github.com/zmokhtar/Memcached-Java-Client/commit/f1229c3bbc463a7e602643fe0ef8aa34ace74e8c

**Comment by newroot** [comment]
Thanks, Zeki

**Comment by mengli** [comment]
close issue due to Zeki's fix
