### ISSUE TITLE
java.lang.OutOfMemoryError  Attempt to allocate stack guard pages failed

### ISSUE THREAD

**Issue by bukebuhao** [gwhalin/Memcached-Java-Client#48]
Exception in thread "http-bio-8080-exec-14" java.lang.OutOfMemoryError
Java HotSpot(TM) Server VM warning: Attempt to allocate stack guard pages failed.
    at sun.misc.Unsafe.allocateMemory(Native Method)
    at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127)
    at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:306)
    at com.schooner.MemCached.SchoonerSockIOPool$TCPSockIO.<init>(Unknown Source)
    at com.schooner.MemCached.SchoonerSockIOFactory.createSocket(Unknown Source)
    at com.schooner.MemCached.SchoonerSockIOFactory.makeObject(Unknown Source)

运行环境 java_memcached-release_2.5.2, tomcat7, jdk7
配置参数-server -Xms1548m -Xmx1548m -Xmn1000m  -XX:PermSize=400m  -XX:MaxPermSize=400m  -XX:ReservedCodeCacheSize=100m
操作系统 Linux version 2.6.18-164.el5 (mockbuild@x86-003.build.bos.redhat.com) (gcc version 4.1.2 20080704 (Red Hat 4.1.2-46)) #1 SMP Tue Aug 18 15:51:48 EDT 2009
cpu 单核 内存 4g，使用2g左右

**Comment by bukebuhao** [comment]
用的是 java_memcached-release_2.6.6,2.5.2没问题

**Comment by newroot** [comment]
你尝试用一下maven里面的最新版。
因为原有域名不在我们控制范围内，从3.0开始我们使用了新域名whalin.com。

请在maven直接搜索com.whalin以及MemcachedJavaClient进行配置。

谢谢！

这个问题是刚启动就有的，还是运行一段时间才会发生的？

**Comment by phoenix** [comment]
java_memcached-2.6.1 今天也遇到这个问题，memcached server不知道怎么回事，运行很久后进程挂掉了，同时我们的4台应用服务器进程全部同时结束，生成hs_err_pid2337.log文件：java.lang.OutOfMemoryError: requested 32756 bytes for ChunkPool::allocate. Out of swap space?

**Comment by bukebuhao** [comment]
先前的服务器，运行了一段时间就会出现Attempt to allocate stack guard pages failed.。 后来发现不只是memcached,其他的模块也一样，甚至jsp编译都出现这种错误。更换了一台服务器，目前为止基本没出现过啦。谢谢
