### ISSUE TITLE
ERROR com.danga.MemCached.MemCachedClien

### ISSUE THREAD

**Issue by jcookies** [gwhalin/Memcached-Java-Client#54]
I have a question, when I use PHP to add data to the Memcache, Java cannot read error! Data format into string! After viewing a MemCachedClient source code, found to be set flags, Java is based on the stored value types for flags, for example: public static final int MARKER_STRING = 32; and PHP is 0, so the question in this place, throw an exception
 example:
 94 [main] ERROR com.danga.MemCached.MemCachedClient - ++++ exception thrown while trying to get object from cache for key: operateLog
 94 [main] ERROR com.danga.MemCached.MemCachedClient - invalid stream header: 71717171
 java.io.StreamCorruptedException: invalid stream header: 71717171
 at java.io.ObjectInputStream.readStreamHeader(Unknown Source)
 at java.io.ObjectInputStream.(Unknown Source)
 at com.schooner.MemCached.ObjectTransCoder.decode(Unknown Source)
 at com.schooner.MemCached.AscIIClient.get(Unknown Source)
 at com.schooner.MemCached.AscIIClient.get(Unknown Source)
 at com.schooner.MemCached.AscIIClient.get(Unknown Source)
 at com.danga.MemCached.MemCachedClient.get(Unknown Source)

**Comment by newroot** [comment]
you can set primitiveasstring or write your own trancoder.
------ 原始邮件 ------

**Comment by mengli** [comment]
Hi jcookies,

Write your own transcoder please.

Meng
