### ISSUE TITLE
BUG in method loadMulti of AscIIClient.java

### ISSUE THREAD

**Issue by chenxiaohu** [gwhalin/Memcached-Java-Client#57]
AscIIClient.java 1203 line should change FROM:

} else if (END.equals(line)) {

TO

} else if ("END".equals(line)) {

because readLine method of ByteBufArrayInputStream use return bos.toString().trim() trim the "\r\n" .

**Comment by mengli** [comment]
Hi chenxiaohu,

Could you please give me an test case to show why you want to make this modification? Otherwise I can't make sure this is a bug.

Meng

**Comment by chenxiaohu** [comment]
I can't give an test case, bug I debug the code, if don't modify, the code below throws exception every time when call com.schooner.MemCached.AscIIClient.loadMulti...

shouldn't happen become always happen. 

```
for (Connection c : conns) {
    try {
        if (c.incoming.size() > 0 && c.isDone())
            loadMulti(new ByteBufArrayInputStream(c.incoming), ret, asString);
        } catch (Exception e) {
            // shouldn't happen; we have all the data already
            log.debug("Caught the aforementioned exception on " + c);
        }
    }   
}
```

# 

```
java.io.IOException: ++++ Stream appears to be dead, so closing it down
    at com.schooner.MemCached.ByteBufArrayInputStream.readLine(Unknown Source)
    at com.schooner.MemCached.AscIIClient.loadMulti(AscIIClient.java:1140)
    at com.schooner.MemCached.AscIIClient.access$300(AscIIClient.java:64)
    at com.schooner.MemCached.AscIIClient$NIOLoader.doMulti(AscIIClient.java:1563)
    at com.schooner.MemCached.AscIIClient.getMulti(AscIIClient.java:1101)
    at com.schooner.MemCached.AscIIClient.getMulti(AscIIClient.java:1025)
    at com.whalin.MemCached.MemCachedClient.getMulti(Unknown Source)
    at com.whalin.MemCached.MemCachedClient.getMulti(Unknown Source)
    at com.schooner.MemCached.MemCachedClientAsciiTest.testGetMulti(Unknown Source)
```

**Comment by mengli** [comment]
Hi chenxiaohu,

It has been fixed in the latest commit. Really thank you for your help!

Meng
