### ISSUE TITLE
Exception with Memcached Java Client 3.0

### ISSUE THREAD

**Issue by venky554** [gwhalin/Memcached-Java-Client#62]
ERROR c.whalin.MemCached.MemCachedClient  - Broken pipe 
java.io.IOException: Broken pipe
    at sun.nio.ch.FileDispatcher.write0(Native Method) ~[na:1.6.0]
    at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:29) ~[na:1.6.0]
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:104) ~[na:1.6.0]
    at sun.nio.ch.IOUtil.write(IOUtil.java:76) ~[na:1.6.0]
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:334) ~[na:1.6.0]
    at com.schooner.MemCached.SchoonerSockIOPool$TCPSockIO.flush(SchoonerSockIOPool.java:1556) ~[Memcached-Java-Client-3.0.JD.1.jar:na]
    at com.schooner.MemCached.BinaryClient.set(BinaryClient.java:344) ~[Memcached-Java-Client-3.0.JD.1.jar:na]
    at com.schooner.MemCached.BinaryClient.cas(BinaryClient.java:276) ~[Memcached-Java-Client-3.0.JD.1.jar:na]

we are using Memcached Java Client in our application and we started see these errors a lot can you let us know what is the fix for this

**Comment by newroot** [comment]
The server is down?

**Comment by mengli** [comment]
Hi venky554,

Please provide more information that we can help you resolve this issue.

Meng
