### ISSUE TITLE
Binary and Ascii clients together in one application

### ISSUE THREAD

**Issue by martinschayna** [gwhalin/Memcached-Java-Client#71]
I have used several Ascii clients in one application, clients were created by `new MemCachedClient()` and the pool was properly initialized with one server. Everything worked fine.

When I try to add one new Binary client via `new MemCachedClient(true)` the Ascii clients stopped working with this call stack:

```
ERROR whalin.MemCached.MemCachedClient - ++++ exception thrown while writing bytes to server on set
ERROR whalin.MemCached.MemCachedClient - 
java.nio.BufferUnderflowException
    at java.nio.Buffer.nextGetIndex(Buffer.java:491)
    at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:223)
    at com.schooner.MemCached.SockInputStream.read(Unknown Source)
    at com.schooner.MemCached.SockInputStream.getLine(Unknown Source)
    at com.schooner.MemCached.AscIIClient.set(Unknown Source)
    at com.schooner.MemCached.AscIIClient.add(Unknown Source)
    at com.whalin.MemCached.MemCachedClient.add(Unknown Source)
        ...
```

When I have tried to replace all Ascii clients with Binary ones, it began to work.

Could I combine Ascii and Binary clients in one app?

**Comment by martinschayna** [comment]
Cleaning up.
