### ISSUE TITLE
java.io.IOException: Connection timed out

### ISSUE THREAD

**Issue by jillsyeda** [gwhalin/Memcached-Java-Client#90]
Hi,I'm use version 3.0.2 and getting below exception:

> 2017-12-07 08:51:50 ERROR com.schooner.MemCached.AscIIClient -1 get - ++++ exception thrown while trying to get object from cache for key: ap_s.sess.user_30
2017-12-07 08:51:50 ERROR com.schooner.MemCached.AscIIClient -1 get - Connection timed out java.io.IOException: Connection timed out
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_152]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_152]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_152]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_152]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_152]
        at com.schooner.MemCached.SockInputStream.<init>(Unknown Source) ~[Memcached-Java-Client-3.0.2.jar:?]
        at com.schooner.MemCached.AscIIClient.get(Unknown Source) [Memcached-Java-Client-3.0.2.jar:?]
        at com.schooner.MemCached.AscIIClient.get(Unknown Source) [Memcached-Java-Client-3.0.2.jar:?]
        at com.schooner.MemCached.AscIIClient.get(Unknown Source) [Memcached-Java-Client-3.0.2.jar:?]
        at com.whalin.MemCached.MemCachedClient.get(Unknown Source) [Memcached-Java-Client-3.0.2.jar:?]
        at com.com4loves.apollo.data.dao.GlobalProtoDAO$1.call(GlobalProtoDAO.java:28) [classes/:?]
        at com.com4loves.apollo.data.dao.GlobalProtoDAO$1.call(GlobalProtoDAO.java:25) [classes/:?]
        at com.com4loves.apollo.data.dao.ProtoDAO.handle(ProtoDAO.java:53) [classes/:?]
        at com.com4loves.apollo.data.dao.GlobalProtoDAO.load(GlobalProtoDAO.java:25) [classes/:?]
        at com.com4loves.apollo.service.SessionService.uninstallOldSession(SessionService.java:62) [classes/:?]
        at com.com4loves.apollo.service.SessionService.create(SessionService.java:45) [classes/:?]
        at com.com4loves.apollo.controller.AccountController.createOrLogin(AccountController.java:66) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) [spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) [spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) [servlet-api.jar:?]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842) [spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.23]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.23]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.23]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.23]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.23]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85) [spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.23]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.23]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:8.5.23]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.23]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [catalina.jar:8.5.23]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.23]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.23]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) [catalina.jar:8.5.23]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.23]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:8.5.23]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-coyote.jar:8.5.23]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.23]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:8.5.23]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-coyote.jar:8.5.23]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.23]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.23]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

My configuration:

> String instance = storage.getAppId() + "_" + entry.getName() + "_" + element.getId();
		SockIOPool pool = SockIOPool.getInstance(instance, true);
		pool.setServers(new String[] { element.getHost() + ":" + element.getPort() });
		pool.setFailover(true);// 设置容错开关
		pool.setInitConn(10);// 设置开始时每个cache服务器的可用连接数
		pool.setMinConn(50);// 设置每个服务器最少可用连接数
		pool.setMaxConn(500);// 设置每个服务器最大可用连接数
		pool.setMaintSleep(30);// 设置连接池维护线程的睡眠时间
		pool.setNagle(false);// 设置是否使用Nagle算法
		pool.setSocketTO(3000);// 设置socket的读取等待超时值
		pool.setAliveCheck(true);// 设置连接心跳监测开关
		pool.initialize();
		initedPools.add(pool);
		MemCachedClient client = new MemCachedClient(instance);
		client.setSanitizeKeys(false);

This exception occurs on the first visit of the day

**Comment by aleksandarlabus** [comment]
Do you have any solution on this issue?
