### ISSUE TITLE
exception thrown while writing bytes to server on set

### ISSUE THREAD

**Issue by santoshsgithub** [gwhalin/Memcached-Java-Client#91]
I am using version 3.0.2. Memcached server version is 1.4.26. I have a legacy system where I want to increase the memcached slab size to 5 MB. When I try to add/set object size more than 1 MB in memcached then I am getting below exception

Dec 11, 2018 12:13:31 PM com.schooner.MemCached.BinaryClient set
SEVERE: ++++ exception thrown while writing bytes to server on set
Dec 11, 2018 12:13:31 PM com.schooner.MemCached.BinaryClient set
SEVERE: Connection reset by peer
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
	at com.schooner.MemCached.SockOutputStream.writeToChannel(Unknown Source)
	at com.schooner.MemCached.SockOutputStream.write(Unknown Source)
	at java.io.ObjectOutputStream$BlockDataOutputStream.write(ObjectOutputStream.java:1842)

Implement WhalinMemcachedJavaClient example :

    private static void implementWhalinMemcachedJavaClient() {
          String[] servers = { "127.0.0.1:11211" };
          SockIOPool sockIOPool = SockIOPool.getInstance("SanTest");

         sockIOPool.setMinConn(2);
         sockIOPool.setMaxConn(20);
         sockIOPool.setServers(servers);
         sockIOPool.setFailover(true);
         sockIOPool.setInitConn(30);
         sockIOPool.setMaintSleep(90);
         sockIOPool.setSocketTO(2000);
         sockIOPool.setAliveCheck(true);
         sockIOPool.setHashingAlg(SockIOPool.NATIVE_HASH);
         sockIOPool.initialize();

         MemCachedClient whalinClient = new MemCachedClient("SanTest", true);
         //MemCachedClient whalinClient = new MemCachedClient("SanTest");

         whalinClient.add("Result", "Success");

         System.out.println("get Result=" + whalinClient.get("Result"));
    }

**Comment by aleksandarlabus** [comment]
@santoshsgithub Do you have any solution for this issue?
